review_app/config/routes.rb
Rails.application.routes.draw do
  get 'reviews/show'
  get 'reviews/index'
  get 'reviews/create'
  get 'reviews/new'
  get 'reviews/edit'
  get 'reviews/update'
  get 'sessions/index'
  # get 'sessions/new'
  resources :sessions
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  get 'profiles/show'
  get 'profiles/new'
  get 'profiles/create'
  get 'profiles/edit'
  get 'profiles/update'
  get 'profile/show'
  get 'profile/new'
  get 'profile/create'
  get 'products/new'
  get 'products/index'
  get 'products/show'
  get 'products/create'
  get 'static_pages/home'
  root 'static_pages#home'
  get 'static_pages/about'
  get 'static_pages/contact'
  resources :products do
    collection do
      get :search
    end
  end
  resources :profiles
  resources :reviews
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

review_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

review_app/app/models/product.rb
class Product < ApplicationRecord
	mount_uploader :productImage, ImageUploader
	has_many :reviews
end

review_app/app/models/profile.rb
class Profile < ApplicationRecord
	mount_uploader :profilePicture, ImageUploader
	has_many :review
end

review_app/app/models/review.rb
class Review < ApplicationRecord
end

review_app/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_uniqueness_of :email
  has_one :profile
end

review_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	def authorize
		redirect_to new_session_path, alert: "Please login or sign up" if current_user.nil?
	end

	private 
	def current_user
		@current_user ||=User.find(session[:user_id]) if session[:user_id]
	end
	helper_method :current_user
end

review_app/app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authorize, :only=> [:create, :new]

  def new
  end

  def index
  	@products = Product.all
  end

  def show
  	@product = Product.find(params[:id])
  end

  def create
  	@product=Product.new(product_params)
  	@product.save
  	redirect_to @product
  end

  def search
    @products = if params[:term]
      Product.where("name LIKE ? OR brand LIKE ?", "%#{params[:term]}", "%#{params[:term]}")
    else
      Product.all
    end
  end

  private
  def product_params
  	params.require(:product).permit(:name, :brand, :averageCost, :category, :releaseDate, :description, :productImage)
  end
end

review_app/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authorize, :only=> [:create, :new, :edit, :update]
  def show
      profile = Profile.find_by(userID: params[:id])
      if !profile
        redirect_to new_profile_path
      else
        @profile = profile
      end
  end

  def new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile["userId"] = current_user.id
    if @profile.save
      redirect_to profile_path(:id => current_user.id), notice:
      "This is your profile"
    else
      render 'new'
    end
  end 

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    if @profile.update(profile_params)
      redirect_to profile_path(:id => @profile['userId'])
    else
      render 'edit'
    end
  end

  private
  def profile_params
  	params.require(:profile).permit(:fullName, :dob, :address, :city, :country, :profilePicture, :productImage)
  end
end

review_app/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :authorize, :only=> [:create, :new, :edit, :update, :destroy]

  def show
  	@review = Review.find(params[:id])
  end

  def index
  	@reviews = Review.where('productId = ' + params['productId'])
  end

  def create
  	@review = Review.new(review_params)
    @review.datePosted = Time.now
    @reviewProfile = Profile.where('userId = ' + current_user.id.to_s).first
    @review["author"] =  @reviewProfile['fullName']
    @review["profileId"] = @reviewProfile['id']
    @review.save
    redirect_to @review
  end

  def new
    @review=Review.new
    @profile=Profile.new
    @product=Product.new
  end

   def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to @review
    else
      render 'edit'
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to reviews_path(:productId => @review.productId)
  end

  private
  def review_params
  	params.require(:review).permit(:rating, :reviewText, :datePosted, :author, :profileId, :productId)
  end
  def reviews_params
    params.require(:reviews).permit(:rating, :reviewText, :datePosted, :author, :profileId, :productId)
  end
end

review_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  	redirect_to root_path
  end

  def new
  end

  def create
  	user=User.find_by_userid(params[ :userid])
  	if user && user.authenticate(params[ :password])
  		session[ :user_id]=user.id
  		redirect_to root_path, notice:
  		"Welcome #{user.userid}, you are logged in"
  	else
  		render 'new', alert:
  		"Invalid username and/or password"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_path, notice:
  	"You have been logged out"
  end
end

review_app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

review_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to root_path, notice:
			"Welcome #{@user.userid}! to Electronic Review App"
		else 
			render 'new'
		end
	end


	private
	  def user_params
	  	params.require(:user).permit(:userid, :email, :password)
	  end
end

review_app/app/helpers/application_helper.rb
module ApplicationHelper
end

review_app/app/helpers/products_helper.rb
module ProductsHelper
end

review_app/app/helpers/profiles_helper.rb
module ProfilesHelper
end

review_app/app/helpers/review_helper.rb
module ReviewHelper
end

review_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

review_app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

review_app/app/helpers/users_helper.rb
module UsersHelper
end

review_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReviewApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

      <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">

        <h5 class="my-0 mr-md-auto font-weight-normal"> Electronic Review App </h5>

        <nav class="my-2 my-md-0 mr-md-3">
          <%= link_to "Home", root_path %>
          <%= link_to "About Us", static_pages_about_path %>
          <%= link_to "Contact Us", static_pages_contact_path %>
          <%= link_to "Products", products_index_path %>
          
          
          <% if current_user %>
            <a class="p-2 text-dark" href="#">
              <%= link_to 'Log Out', session_path('active'), method: :delete %>
            </a>
            <a class="p-2 text-dark" href='#'>
              <%= link_to current_user.userid, profiles_show_path(:id => current_user.id) %>
            </a>
          <% else %>
            <a class="p-2 text-dark" href="#">
              <%= link_to 'Log In', new_session_path, class: "active-nav-link" %>
            </a>
            <a class="p-2 text-dark" href="#">
              <%= link_to "Register", new_user_path, class: "active-nav-link" %>
            </a>
          <% end %>
       </nav>
      </div>
    </div>
    <div class="container">
      <% if notice %> <%= notice %> <%end%>
      <% if alert %> <<%= alert %> <%end%>
      <%= yield %>
    </div>
  </body>
</html>

review_app/app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

review_app/app/views/products/index.html.erb
<div class="container">
	<h2>Products</h2>
	<%= link_to 'Add New Product', products_new_path %>
	<table border="1" class="table products-table">
		<tr>
			<th> Product Name </th>
			<th> Brand</th>
			<th> Average Price </th>
			<th> Category </th>
			<th> Release Date </th>
			<th> Description </th>
			<th> Image </th>
			<th> Actions </th>

		</tr>
		<% @products.each do |product| %>
			<tr>
				<td> <%= product.name %> </td>
				<td> <%= product.brand %> </td>
				<td> <%= product.averageCost %> </td>
				<td> <%= product.category %> </td>
				<td> <%= product.releaseDate %> </td>
				<td> <%= product.description %> </td>
				<td> <%= image_tag(product.productImage.url, alt: 'Image') if product.productImage? %> </td>
				<td> 
					<%= link_to 'Product Page', product_path(product) %> 
					<%= link_to 'View Reviews', reviews_index_path(:productId => product.id) %>
					<%= link_to 'Write Review', reviews_new_path(:id => product.id) %> 
				</td>
			</tr>
		<% end %>
	</table>
</div>

review_app/app/views/products/new.html.erb
<div class="container">
	<h1 class="jumbotron-heading">Add New Product</h1>

	<%= form_for :product, url: products_path do |f| %>
		<div class="form-group">
			<%= f.label :name %>
			<%= f.text_field :name, class:'form-control'%>
			<%= f.label :brand %>
			<%= f.text_field :brand , class:'form-control'%>
			<%= f.label :averageCost %>
			<%= f.number_field :averageCost , class:'form-control'%>
			<%= f.label :category %>
			<%= f.text_field :category , class:'form-control'%>
			<%= f.label :releaseDate %>
			<%= f.date_field :releaseDate, class:'form-control'%>
			<%= f.label :description %>
			<%= f.text_area :description , class:'form-control'%>
			<%= f.label :productImage %>
			<%= f.file_field :productImage , class:'form-control'%>
			<%= f.submit %>
		</div>
	<% end %>

</div>

review_app/app/views/products/search.html.erb
<div class="container">
	<h2>Products</h2>
	<%= form_tag search_products_path, method: :get do%>
		<%= text_field_tag :term, nil, placeholder: "Search", class:"form-control"%>
		<%= submit_tag "Search", class:"btn btn-default"%>
	<%end%>
	<%= link_to 'Add New Product', products_new_path %>
	<table border="1" class="table products-table">
		<tr>
			<th> Product Name </th>
			<th> Brand</th>
			<th> Average Price </th>
			<th> Category </th>
			<th> Release Date </th>
			<th> Description </th>
			<th> Image </th>
			<th> Actions </th>

		</tr>
		<% @products.each do |product| %>
			<tr>
				<td> <%= product.name %> </td>
				<td> <%= product.brand %> </td>
				<td> <%= product.averageCost %> </td>
				<td> <%= product.category %> </td>
				<td> <%= product.releaseDate %> </td>
				<td> <%= product.description %> </td>
				<td> <%= image_tag(product.productImage.url, alt: 'Image') if product.productImage? %> </td>
				<td> 
					<%= link_to 'View Product', product_path(product) %> | 
					<%= link_to 'View Reviews', reviews_index_path(:productId => product.id) %> | 
					<%= link_to 'Write Review', reviews_new_path(:id => product.id) %> 
				</td>
			</tr>
		<% end %>
	</table>
</div>

review_app/app/views/products/show.html.erb
<div class="container">
	<h3>Product Details</h3>
		
<div class="product-container">
		<p class="picture text-center"> <%= image_tag(@product.productImage.url, alt: 'Image') if @product.productImage? %> </p>
			<div class="text-center">
				<p> Product Name: <%= @product.name%> </p>
				<p> Brand: <%= @product.brand%> </p>
				<p> Average Price: <%= @product.averageCost%> </p>
				<p> Category: <%= @product.category%> </p>
				<p> Release Date: <%= @product.releaseDate%> </p>
				<p> Description: <%= @product.description%> </p>
				<%= link_to 'View Reviews', reviews_index_path(:productId => @product.id) %> | 
				<%= link_to 'Write Review', reviews_new_path(:id => @product.id) %> 
			</div>
			
	</div>


</div>

review_app/app/views/profiles/create.html.erb
<h1>Profiles#create</h1>
<p>Find me in app/views/profiles/create.html.erb</p>

review_app/app/views/profiles/edit.html.erb
<div class="container">
	<h1 class="jumbotron-heading">Edit Your Profile</h1>

	<%= form_for @profile do |f| %>
		<div class="form-group">
			<%= f.label :fullName %>
			<%= f.text_field :fullName, class:'form-control'%>
			<%= f.label :dob %>
			<%= f.date_field :dob , class:'form-control'%>
			<%= f.label :address %>
			<%= f.text_field :address , class:'form-control'%>
			<%= f.label :city %>
			<%= f.text_field :city , class:'form-control'%>
			<%= f.label :country %>
			<%= f.text_field :country, class:'form-control'%>
			<%= f.label :profilePicture %>
			<%= f.file_field :profilePicture , class:'form-control'%>
			<%= f.submit %>
		</div>
	<% end %>

</div>

review_app/app/views/profiles/new.html.erb
<div class="container">
	<h1 class="jumbotron-heading">Register</h1>

	<%= form_for :profile, url: profiles_path do |f| %>
		<div class="form-group">
			<%= f.label :fullName %>
			<%= f.text_field :fullName, class:'form-control'%>
			<%= f.label :dob %>
			<%= f.date_field :dob , class:'form-control'%>
			<%= f.label :address %>
			<%= f.text_field :address , class:'form-control'%>
			<%= f.label :city %>
			<%= f.text_field :city , class:'form-control'%>
			<%= f.label :country %>
			<%= f.text_field :country, class:'form-control'%>
			<%= f.label :profilePicture %>
			<%= f.file_field :profilePicture , class:'form-control'%>
			<%= f.submit %>
		</div>
	<% end %>

</div>

review_app/app/views/profiles/show.html.erb
<div class="container">
	<h3>Profile Details</h3>
	<div class="profile-container">
		<p class="picture text-center"> <%= image_tag(@profile.profilePicture.url, alt: 'Image') if @profile.profilePicture? %> </p>
			<div class="text-center">
				<p class="text-center"> Full Name: <%= @profile.fullName%> </p>
				<p> Date Of Birth: <%= @profile.dob%> </p>
				<p> Address: <%= @profile.address%> </p>
				<p> City: <%= @profile.city%> </p>
				<p> Country: <%= @profile.country%> </p>
			</div>
		<p class="text-center"> <%= link_to "Edit My Profile", edit_profile_path(@profile)%></p>
	</div>
</div>

review_app/app/views/review/index.html.erb
<div class="container">
	<h2>Reviews For PRODUCTNAME</h2>
	<table border="1" class="table">
		<tr>
			<th> Rating </th>
			<th> Review Text</th>
			<th> Date Posted </th>
			<th> Author </th>
			<th> View Review </th>
		</tr>
		<% @reviews.each do |review| %>
			<tr>
				<td> <%= review.rating %> </td>
				<td> <%= review.reviewText %> </td>
				<td> <%= review.datePosted %> </td>
				<td> <%= review.author %> </td>
				<td> <%= link_to 'Review Page', review_path(review) %> </td>
			</tr>
		<% end %>
	</table>
</div>

review_app/app/views/reviews/create.html.erb
<h1>Review#create</h1>
<p>Find me in app/views/review/create.html.erb</p>

review_app/app/views/reviews/edit.html.erb
<div class="container">
	<h1 class="jumbotron-heading">Edit Your Review</h1>

	<%= form_for @review do |f| %>
		<div class="form-group">
			<%= f.label :rating %>
			<%= f.select :rating, [[1,1], [2,2], [3,3], [4,4], [5,5]], class:'form-control'%>
			<%= f.label :reviewText %>
			<%= f.text_area :reviewText , class:'form-control'%>
			<%= f.submit %>
		</div>
	<% end %>

</div>

review_app/app/views/reviews/index.html.erb
<div class="container">
	<h2>Reviews For <%= Product.where(id: params['productId']).pluck(:name).first %></h2>
	<table border="1" class="table reviews-table">
		<tr>
			<th> Rating </th>
			<th> Review Text</th>
			<th> Date Posted </th>
			<th> Author </th>
			<th> Profile Picture </th>
			<th> Actions</th>
		</tr>
		<% @reviews.each do |review| %>
			<tr>
				<td> <%= review.rating %> </td>
				<td> <%= review.reviewText %> </td>
				<td> <%= review.datePosted %> </td>
				<td> <%= review.author %> </td>
				<td> <img src="/uploads/profile/profilePicture/<%=review.profileId%>/<%=Profile.where(id: review.profileId).pluck(:profilePicture).first%>">
				<td> 
					<%= link_to 'View Review', review_path(review) %> | 
					<%= link_to 'Edit', edit_review_path(review) %> | 
					<%= link_to 'Delete', review_path(review), method: :Delete, data: {confirm: "Are you sure you want to delete this review"}%> 
				</td>
			</tr>
		<% end %>
	</table>
</div>

review_app/app/views/reviews/new.html.erb
<div class="container">
	<h1 class="jumbotron-heading">Add New Review</h1>

	<%= form_for :review, url: reviews_path do |f| %>
		<div class="form-group">
			<%= f.label :rating %>
			<%= f.select :rating, [[1,1], [2,2], [3,3], [4,4], [5,5]], class:'form-control'%>
			<%= f.label :reviewText %>
			<%= f.text_area :reviewText , class:'form-control'%>
			<%= f.hidden_field :productId, value: params['id']%>
			<%= f.submit %>
		</div>
	<% end %>

</div>

review_app/app/views/reviews/show.html.erb
<div class="container">
	<h3>Review Details</h3>
	<p> Rating: <%= @review.rating%> </p>
	<p> Review: <%= @review.reviewText%> </p>
	<p> Author: <%= @review.author%> </p>
	<p> Date: <%= @review.datePosted%> </p>
</div>

review_app/app/views/static_pages/about.html.erb
<div class="container">
	<h1 class="jumbotron-heading">About Us</h1>

	<div class="container">
		<div class="row">
			<div class="col">
				<p>
					Quisque venenatis rhoncus ligula, at malesuada velit semper sed. Nulla et congue sapien, at efficitur justo. Phasellus eu sapien vitae lacus convallis dapibus. Mauris nisi magna, accumsan in urna et, maximus venenatis sapien. Pellentesque quis lobortis nunc. Nullam ultrices nec justo et ornare. Sed id porttitor augue.
				</p>
			</div>
			<div class="col">
				<p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas a justo vehicula, consectetur magna a, facilisis nibh. Nam nec lacus sit amet augue faucibus pretium. Aliquam eu imperdiet mauris. Nulla scelerisque nunc a dolor pharetra sagittis. Nullam vel finibus orci. Curabitur dapibus, nulla a suscipit aliquam, nisl sapien congue enim, sed consequat dui elit vitae libero. Etiam scelerisque sapien magna, vitae consequat arcu volutpat a. Praesent id massa nec ante maximus tincidunt eget vel purus. Integer a iaculis tortor, sit amet sollicitudin lacus. Etiam pulvinar ultrices orci, eget mattis enim. Pellentesque ut vehicula mauris. Curabitur a efficitur eros, non semper justo. Duis et felis nunc. Aenean sed risus at erat viverra bibendum. Praesent vulputate porta fringilla. Pellentesque purus urna, accumsan non hendrerit at, lacinia eget est.
				</p>
			</div>
		</div>
	</div>
</div>

review_app/app/views/static_pages/contact.html.erb
<div class="container">
	<h1 class="jumbotron-heading">Contact Us</h1>

	<div class="container">
		<form>
			<div>
				name:
				<input type="text">
			</div>
			<div>
				email:
				<input type="text">
			</div>
			<div>
				subject:
				<input type="text">
			</div>
			<div>
				enquiry:
				<textarea rows="3">
				</textarea>
			</div>
			<button>Send</button>
		</form>
	</div>
</div>

review_app/app/views/static_pages/home.html.erb
<div class="container">
	<h1 class="jumbotron-heading">Home</h1>

	<div class="container">
		<div class="row">
			<div class="col">
				<p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas a justo vehicula, consectetur magna a, facilisis nibh. Nam nec lacus sit amet augue faucibus pretium. Aliquam eu imperdiet mauris. Nulla scelerisque nunc a dolor pharetra sagittis. Nullam vel finibus orci. Curabitur dapibus, nulla a suscipit aliquam, nisl sapien congue enim, sed consequat dui elit vitae libero. Etiam scelerisque sapien magna, vitae consequat arcu volutpat a. Praesent id massa nec ante maximus tincidunt eget vel purus. Integer a iaculis tortor, sit amet sollicitudin lacus. Etiam pulvinar ultrices orci, eget mattis enim. Pellentesque ut vehicula mauris. Curabitur a efficitur eros, non semper justo. Duis et felis nunc. Aenean sed risus at erat viverra bibendum. Praesent vulputate porta fringilla. Pellentesque purus urna, accumsan non hendrerit at, lacinia eget est.
				</p>
			</div>
			<div class="col">
				<p>
					Quisque venenatis rhoncus ligula, at malesuada velit semper sed. Nulla et congue sapien, at efficitur justo. Phasellus eu sapien vitae lacus convallis dapibus. Mauris nisi magna, accumsan in urna et, maximus venenatis sapien. Pellentesque quis lobortis nunc. Nullam ultrices nec justo et ornare. Sed id porttitor augue.
				</p>
			</div>
		</div>
	</div>
</div>

review_app/app/views/users/new.html.erb
<div class="container">
	<h2> Create User Account </h2>
	<%= form_for @user do |f| %>
	<div class="field" style="100%">
		<% if @user.errors.any? %>
			<div id="error_explaination">
				<h2>
					<%= pluralize(@user.errors.count, "error") %>
					Prohibited this from being saved
				</h2>
				<p>
					<ul>
						<% @user.errors.full_messages.each do |msg| %>
							<li>
								<%= msg %>
							</li>
						<% end %>
					</ul>
				</p>
				<% if alert %>
					<%= alert %>
				<% end %>
			</div>
		<% end %>
		<%= f.text_field :userid, placeholder: "Enter a Username", class: 'form-control' %>
		<%= f.text_field :email, placeholder: "Enter your Email Address", class: 'form-control' %>
		<%= f.password_field :password, placeholder: "Create a Password", class: 'form-control' %>
		<%= f.password_field :password_confirmation, placeholder: "Confirm your Password", class: 'form-control' %>
		<%= f.submit 'Create Account' %>
		<% end %>
	</div>
</div>